web:
  build: .
  command: run --debug --collect-static --db-migrate --db-timeout 10 --bind 0.0.0.0:5000
  ports:
   - "5001:5000"
  links:
   - postgres
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./data:/code/data
   - ./dockci:/code/dockci
   - ./alembic:/code/alembic
   - /Users:/Users
  environment:
    OAUTHLIB_INSECURE_TRANSPORT: true
postgres:
  image: postgres
  environment:
    POSTGRES_USER: dockci
    POSTGRES_PASSWORD: letmein
registry:
  image: registry:2
  ports:
   - "5000:5000"
