web:
  build: .
  command: run --debug --db-migrate --db-timeout 10 --bind 0.0.0.0:5000
  ports:
   - "5001:5000"
  links:
   - postgres
   - registry
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./dockci:/code/dockci
postgres:
  image: postgres
  environment:
    POSTGRES_USER: dockci
    POSTGRES_PASSWORD: letmein
registry:
  image: registry:2
