web:
  build: .
  command: run --debug --collect-static --db-migrate --timeout 15 --bind 0.0.0.0:5000
  ports:
   - "5001:5000"
  links:
   - postgres
   - rabbitmq
   - redis
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - ./data:/code/data
   - ./dockci:/code/dockci
   - ./alembic:/code/alembic
   - ./tests:/code/tests
   - /Users:/Users
  environment:
    OAUTHLIB_INSECURE_TRANSPORT: 1
postgres:
  image: postgres
  environment:
    POSTGRES_USER: dockci
    POSTGRES_PASSWORD: letmein
rabbitmq:
  image: sprucedev/dockci-rabbitmq
  ports:
    - "15674:15674"  # Web STOMP
    - "5672"         # AMQP
    - "15672"        # Management interface
  environment:
    FRONTEND_USER: dockcife
    FRONTEND_PASSWORD: letmein
    BACKEND_USER: dockcibe
    BACKEND_PASSWORD: changeme
redis:
  image: redis
registry:
  image: registry:2
  ports:
   - "5000:5000"
