"""nullable email user relation

Revision ID: 177f9d0e8ba
Revises: 289566f9de2
Create Date: 2016-04-22 07:08:14.983385

"""

# revision identifiers, used by Alembic.
revision = '177f9d0e8ba'
down_revision = '289566f9de2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_email', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_email', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
